INSERT INTO Stock
    (symbol,company,timeData,last_query)
VALUES
    ('AMZN', 'Amazone', '5', NOW()),
    ('TSLA', 'Tesla', '5', NOW()),
    ('YHOO', 'Yahoo', '5', NOW()),
    ('CELG', 'Celgene', '5', NOW()),
    ('FCEL', 'Fuelcell Energy', '5', NOW()),
    ('AAPL', 'Apple', '5', NOW()),
    ('INTC', 'Intel', '5', NOW()),
    ('MRVL', 'Marvel', '5', NOW()),
    ('ICFI', 'Ico', '5', NOW()),
    ('IGOI', 'IGO', '5', NOW()),
    ('IMAX', 'Imax', '5', NOW()),
    ('IRIS', 'Iris', '5', NOW()),
    ('ITRI', 'Itron', '5', NOW()),
    ('IXYS', 'IXYS', '5', NOW()),
    ('IMAX', 'Imax', '5', NOW()),
    ('AAPL', 'Apple Inc.', '5', NOW()),
    ('XOM', 'Exxon Mobil Corporation', '5', NOW()),
    ('MSFT', 'Microsoft Corporation', '5', NOW()),
    ('BAC^I', 'Bank of America Corporation', '5', NOW()),
    ('IBM', 'International Business Machines Corporation', '5', NOW()),
    ('CVX', 'Chevron Corporation', '5', NOW()),
    ('GE', 'General Electric Company', '5', NOW()),
    ('WMT', 'Wal-Mart Stores', '5', NOW()),
    ('T', ' Inc.', '5', NOW()),
    ('JNJ', 'AT&T Inc.', '5', NOW()),
    ('PG', 'Johnson & Johnson', '5', NOW()),
    ('WFC', 'Procter & Gamble Company (The)', '5', NOW()),
    ('KO', 'Wells Fargo & Company', '5', NOW()),
    ('PFE', 'Coca-Cola Company (The)', '5', NOW()),
    ('JPM', 'Pfizer', '5', NOW()),
    ('GOOG', ' Inc.', '5', NOW()),
    ('PM', 'J P Morgan Chase & Co', '5', NOW()),
    ('VOD', 'Google Inc.', '5', NOW()),
    ('ORCL', 'Philip Morris International Inc', '5', NOW()),
    ('INTC', 'Vodafone Group Plc', '5', NOW()),
    ('MRK', 'Oracle Corporation', '5', NOW()),
    ('VZ', 'Intel Corporation', '5', NOW()),
    ('BRK/A', 'Merck & Company', '5', NOW()),
    ('QCOM', ' Inc.', '5', NOW()),
    ('PEP', 'Verizon Communications Inc.', '5', NOW()),
    ('CSCO', 'Berkshire Hathaway Inc.', '5', NOW()),
    ('AMZN', 'QUALCOMM Incorporated', '5', NOW()),
    ('ABT', 'Pepsico', '5', NOW()),
    ('MCD', ' Inc.', '5', NOW()),
    ('SLB', 'Cisco Systems', '5', NOW()),
    ('C', ' Inc.', '5', NOW()),
    ('BRK/B', 'Amazon.com', '5', NOW()),
    ('BAC', ' Inc.', '5', NOW()),
    ('RY', 'Abbott Laboratories', '5', NOW()),
    ('HD', 'McDonald&#39;s Corporation', '5', NOW()),
    ('DIS', 'Schlumberger N.V.', '5', NOW()),
    ('TD', 'Citigroup Inc.', '5', NOW()),
    ('UTX', 'Berkshire Hathaway Inc.', '5', NOW()),
    ('OXY', 'Bank of America Corporation', '5', NOW()),
    ('AXP', 'Royal Bank Of Canada', '5', NOW()),
    ('KFT', 'Home Depot', '5', NOW()),
    ('COP', ' Inc. (The)', '5', NOW()),
    ('MO', 'Walt Disney Company (The)', '5', NOW()),
    ('CAT', 'Toronto Dominion Bank (The)', '5', NOW()),
    ('V', 'United Technologies Corporation', '5', NOW()),
    ('CMCSA', 'Occidental Petroleum Corporation', '5', NOW()),
    ('MMM', 'American Express Company', '5', NOW()),
    ('USB', 'Kraft Foods Inc.', '5', NOW()),
    ('AIG', 'ConocoPhillips', '5', NOW()),
    ('EMC', 'Altria Group', '5', NOW()),
    ('CVS', 'Caterpillar', '5', NOW()),
    ('BNS', ' Inc.', '5', NOW()),
    ('UNH', 'Visa Inc.', '5', NOW()),
    ('BA', 'Comcast Corporation', '5', NOW()),
    ('UPS', '3M Company', '5', NOW()),
    ('BMY', 'U.S. Bancorp', '5', NOW()),
    ('AMGN', 'American International Group', '5', NOW()),
    ('UNP', ' Inc.', '5', NOW()),
    ('GS', 'EMC Corporation', '5', NOW()),
    ('MA', 'CVS Corporation', '5', NOW()),
    ('EBAY', 'Bank of Nova Scotia (The)', '5', NOW()),
    ('DD', 'UnitedHealth Group Incorporated', '5', NOW()),
    ('HPQ', 'Boeing Company (The)', '5', NOW()),
    ('LLY', 'United Parcel Service', '5', NOW()),
    ('CL', ' Inc.', '5', NOW()),
    ('SU', 'Bristol-Myers Squibb Company', '5', NOW()),
    ('SPG', 'Amgen Inc.', '5', NOW()),
    ('EPD', 'Union Pacific Corporation', '5', NOW()),
    ('HON', 'Goldman Sachs Group', '5', NOW()),
    ('LVS', ' Inc. (The)', '5', NOW()),
    ('ESRX', 'Mastercard Incorporated', '5', NOW()),
    ('SBUX', 'eBay Inc.', '5', NOW()),
    ('NKE', 'E.I. du Pont de Nemours and Company', '5', NOW()),
    ('ACN', 'Hewlett-Packard Company', '5', NOW()),
    ('F', 'Eli Lilly and Company', '5', NOW()),
    ('MDT', 'Colgate-Palmolive Company', '5', NOW()),
    ('SO', 'Suncor Energy  Inc.', '5', NOW()),
    ('MON', 'Simon Property Group', '5', NOW()),
    ('TEVA', ' Inc.', '5', NOW()),
    ('DOW', 'Enterprise Products Partners L.P.', '5', NOW()),
    ('GILD', 'Honeywell International Inc.', '5', NOW()),
    ('ABX', 'Las Vegas Sands Corp.', '5', NOW()),
    ('IMO', 'Express Scripts Holding Company', '5', NOW()),
    ('LOW', 'Starbucks Corporation', '5', NOW()),
    ('DHR', 'Nike', '5', NOW()),
    ('CNI', ' Inc.', '5', NOW()),
    ('DB', 'Accenture plc.', '5', NOW()),
    ('TGT', 'Ford Motor Company', '5', NOW()),
    ('PCLN', 'Medtronic', '5', NOW()),
    ('BMO', ' Inc.', '5', NOW()),
    ('POT', 'Southern Company (The)', '5', NOW()),
    ('MET', 'Monsanto Company', '5', NOW()),
    ('COST', 'Teva Pharmaceutical Industries Limited', '5', NOW()),
    ('EMR', 'Dow Chemical Company (The)', '5', NOW()),
    ('BIDU', 'Gilead Sciences', '5', NOW()),
    ('TXN', ' Inc.', '5', NOW()),
    ('GM', 'Barrick Gold Corporation', '5', NOW()),
    ('TWX', 'Imperial Oil Limited', '5', NOW()),
    ('CNQ', 'Lowe&#39;s Companies', '5', NOW()),
    ('FCX', ' Inc.', '5', NOW()),
    ('APC', 'Danaher Corporation', '5', NOW()),
    ('PNC', 'Canadian National Railway Company', '5', NOW()),
    ('PX', 'Deutsche Bank AG', '5', NOW()),
    ('APA', 'Target Corporation', '5', NOW()),
    ('BP', 'priceline.com Incorporated', '5', NOW()),
    ('YUM', 'Bank Of Montreal', '5', NOW()),
    ('DTV', 'Potash Corporation of Saskatchewan Inc.', '5', NOW()),
    ('DE', 'MetLife', '5', NOW()),
    ('NWSA', ' Inc.', '5', NOW()),
    ('QQQ', 'Costco Wholesale Corporation', '5', NOW()),
    ('MS', 'Emerson Electric Company', '5', NOW()),
    ('BCE', 'Baidu', '5', NOW()),
    ('ENB', ' Inc.', '5', NOW()),
    ('BIIB', 'Texas Instruments Incorporated', '5', NOW()),
    ('TJX', 'General Motors Company', '5', NOW()),
    ('KMB', 'Time Warner Inc.', '5', NOW()),
    ('CELG', 'Canadian Natural Resources Limited', '5', NOW()),
    ('BAX', 'Freeport-McMoran Copper & Gold', '5', NOW()),
    ('TRP', ' Inc.', '5', NOW()),
    ('NOV', 'Anadarko Petroleum Corporation', '5', NOW()),
    ('HAL', 'PNC Financial Services Group', '5', NOW()),
    ('D', ' Inc. (The)', '5', NOW()),
    ('GG', 'Praxair', '5', NOW()),
    ('CM', ' Inc.', '5', NOW()),
    ('MCI', 'Apache Corporation', '5', NOW()),
    ('WAG', 'BP p.l.c.', '5', NOW()),
    ('RDS/A', 'Yum! Brands', '5', NOW()),
    ('DUK', ' Inc.', '5', NOW()),
    ('LMT', 'DIRECTV', '5', NOW()),
    ('DELL', 'Deere & Company', '5', NOW()),
    ('EOG', 'News Corporation', '5', NOW()),
    ('AGN', 'PowerShares QQQ Trust', '5', NOW()),
    ('FDX', ' Series 1', '5', NOW()),
    ('ERIC', 'Morgan Stanley', '5', NOW()),
    ('BK', 'BCE', '5', NOW()),
    ('SCCO', ' Inc.', '5', NOW()),
    ('ITW', 'Enbridge Inc', '5', NOW()),
    ('NEE', 'Biogen Idec Inc.', '5', NOW()),
    ('DVN', 'TJX Companies', '5', NOW()),
    ('ADP', ' Inc. (The)', '5', NOW()),
    ('AMT', 'Kimberly-Clark Corporation', '5', NOW()),
    ('COV', 'Celgene Corporation', '5', NOW()),
    ('INFY', 'Baxter International Inc.', '5', NOW()),
    ('ACE', 'Transcanada Pipelines', '5', NOW()),
    ('BLK', ' Ltd.', '5', NOW()),
    ('EXC', 'National-Oilwell', '5', NOW()),
    ('TYC', ' Inc.', '5', NOW()),
    ('BEN', 'Halliburton Company', '5', NOW()),
    ('PCP', 'Dominion Resources', '5', NOW()),
    ('TRV', ' Inc.', '5', NOW()),
    ('COF', 'Goldcorp Incorporated', '5', NOW()),
    ('KMI', 'Canadian Imperial Bank of Commerce', '5', NOW()),
    ('PRU', 'Babson Capital Corporate Investors', '5', NOW()),
    ('GIS', 'Walgreen Co.', '5', NOW()),
    ('TWC', 'Royal Dutch Shell PLC', '5', NOW()),
    ('TRI', 'Duke Energy Corporation', '5', NOW()),
    ('CVE', 'Lockheed Martin Corporation', '5', NOW()),
    ('GD', 'Dell Inc.', '5', NOW()),
    ('PSA', 'EOG Resources', '5', NOW()),
    ('AMX', ' Inc.', '5', NOW()),
    ('CTL', 'Allergan', '5', NOW()),
    ('VIAB', ' Inc.', '5', NOW()),
    ('NSC', 'FedEx Corporation', '5', NOW()),
    ('RAI', 'Ericsson', '5', NOW()),
    ('CSX', 'Bank Of New York Mellon Corporation (The)', '5', NOW()),
    ('MFC', 'Southern Copper Corporation', '5', NOW()),
    ('LYB', 'Illinois Tool Works Inc.', '5', NOW()),
    ('NEM', 'NextEra Energy', '5', NOW()),
    ('ISRG', ' Inc.', '5', NOW()),
    ('STT', 'Devon Energy Corporation', '5', NOW()),
    ('BBT', 'Automatic Data Processing', '5', NOW()),
    ('WLP', ' Inc.', '5', NOW()),
    ('JCI', 'American Tower Corporation (REIT)', '5', NOW()),
    ('ADM', 'Covidien plc.', '5', NOW()),
    ('MPV', 'Infosys Limited', '5', NOW()),
    ('CTSH', 'Ace Limited', '5', NOW()),
    ('MCK', 'BlackRock', '5', NOW()),
    ('CRM', ' Inc.', '5', NOW()),
    ('COH', 'Exelon Corporation', '5', NOW()),
    ('EP', 'Tyco International', '5', NOW()),
    ('GLW', ' Ltd. (Switzerland)', '5', NOW()),
    ('CMI', 'Franklin Resources', '5', NOW()),
    ('SYK', ' Inc.', '5', NOW()),
    ('AFL', 'Precision Castparts Corporation', '5', NOW()),
    ('CBS', 'The Travelers Companies', '5', NOW()),
    ('BAM', ' Inc.', '5', NOW()),
    ('TCK', 'Capital One Financial Corporation', '5', NOW()),
    ('ASML', 'Kinder Morgan', '5', NOW()),
    ('CB', ' Inc.', '5', NOW()),
    ('TMO', 'Prudential Financial', '5', NOW()),
    ('SE', ' Inc.', '5', NOW()),
    ('FE', 'General Mills', '5', NOW()),
    ('WMB', ' Inc.', '5', NOW()),
    ('CCL', 'Time Warner Cable Inc', '5', NOW()),
    ('KMP', 'Thomson Reuters Corp', '5', NOW()),
    ('PSX', 'Cenovus Energy Inc', '5', NOW()),
    ('MRO', 'General Dynamics Corporation', '5', NOW()),
    ('EQR', 'Public Storage', '5', NOW()),
    ('PCG', 'America Movil', '5', NOW()),
    ('AEP', ' S.A.B. de C.V.', '5', NOW()),
    ('MMC', 'CenturyLink', '5', NOW()),
    ('ECL', ' Inc.', '5', NOW()),
    ('YHOO', 'Viacom Inc.', '5', NOW()),
    ('SHPGY', 'Norfolk Souther Corporation', '5', NOW()),
    ('CMCSK', 'Reynolds American Inc', '5', NOW()),
    ('APD', 'CSX Corporation', '5', NOW()),
    ('BHI', 'Manulife Financial Corp', '5', NOW()),
    ('K', 'LyondellBasell Industries NV', '5', NOW()),
    ('RTN', 'Newmont Mining Corporation (Holding Company)', '5', NOW()),
    ('GSK', 'Intuitive Surgical', '5', NOW()),
    ('DFS', ' Inc.', '5', NOW()),
    ('WPZ', 'State Street Corporation', '5', NOW()),
    ('SDRL', 'BB&T Corporation', '5', NOW()),
    ('HES', 'WellPoint Inc.', '5', NOW()),
    ('NFLX', 'Netflix', '5', NOW());