DROP DATABASE IF EXISTS libra;

CREATE DATABASE libra;

use libra;

CREATE TABLE User (
        id INTEGER NOT NULL AUTO_INCREMENT,
        username varchar (255) NOT NULL,
        password varchar (255) NOT NULL,
        email varchar (255) NOT NULL,
        creationdate varchar (512) NOT NULL,
        PRIMARY KEY (id)
);

CREATE TABLE UserAction (
        id INTEGER NOT NULL AUTO_INCREMENT,
        userID INTEGER NOT NULL,
        activity varchar (255),
        accurance datetime,
        status varchar (255),
        PRIMARY KEY (id),
        FOREIGN KEY (userID) REFERENCES User (id)
);

CREATE TABLE transaction (
        id INTEGER NOT NULL AUTO_INCREMENT,
        userID INTEGER NOT NULL,
        action varchar (255),
        symbol varchar (255),
        amount INTEGER,
        value Decimal (50, 10),
        date date,
        processed boolean,
        PRIMARY KEY (id),
        FOREIGN KEY (userID) REFERENCES User (id)
);

CREATE TABLE stock (
        id INTEGER AUTO_INCREMENT,
        symbol varchar (255),
        company varchar (255),
        timeData ENUM ('Daily', '5', '15', '30', '60'),
        data LONGTEXT,
        price varchar (255),
        last_query DATETIME,
        PRIMARY KEY (id)
);

CREATE TABLE Portfolio (
        id INTEGER AUTO_INCREMENT,
        user_id INTEGER,
        current_value Decimal (50, 10),
        total_stocks INTEGER,
        balance Decimal (50, 10),
        start_capital Decimal (50, 10),
        PRIMARY KEY (id),
        FOREIGN KEY (user_id) REFERENCES User (id)
);

CREATE TABLE portfolio_item (
        id INTEGER AUTO_INCREMENT,
        stock_id INTEGER,
        buy_price Decimal (50, 10),
        buy_date_time DATETIME,
        quantity INTEGER,
        total_buy_price Decimal (50, 10),
        PRIMARY KEY (id),
        FOREIGN KEY (stock_id) REFERENCES stock (id)
);

CREATE TABLE portfolio_to_item (
        id INTEGER AUTO_INCREMENT,
        portfolio_id INTEGER,
        portfolio_item_id INTEGER,
        PRIMARY KEY (id),
        FOREIGN KEY (portfolio_id) REFERENCES Portfolio (id),
        FOREIGN KEY (portfolio_item_id) REFERENCES portfolio_item (id)
);

CREATE TABLE performance (
        id INTEGER,
        userID INTEGER,
        date date,
        performance DECIMAL(10, 2),
        PRIMARY KEY (id),
        FOREIGN KEY (userID) REFERENCES User (id)
);

INSERT INTO
        stock (symbol, timeData, last_query)
VALUES
        ('AAPL', '5', NOW()),
        ('XOM', '5', NOW()),
        ('MSFT', '5', NOW()),
        ('BAC^I', '5', NOW()),
        ('IBM', '5', NOW()),
        ('CVX', '5', NOW()),
        ('GE', '5', NOW()),
        ('WMT', '5', NOW()),
        ('T', '5', NOW()),
        ('JNJ', '5', NOW()),
        ('PG', '5', NOW()),
        ('WFC', '5', NOW()),
        ('KO', '5', NOW()),
        ('PFE', '5', NOW()),
        ('JPM', '5', NOW()),
        ('GOOG', '5', NOW()),
        ('PM', '5', NOW()),
        ('VOD', '5', NOW()),
        ('ORCL', '5', NOW()),
        ('INTC', '5', NOW()),
        ('MRK', '5', NOW()),
        ('VZ', '5', NOW()),
        ('BRK/A', '5', NOW()),
        ('QCOM', '5', NOW()),
        ('PEP', '5', NOW()),
        ('CSCO', '5', NOW()),
        ('AMZN', '5', NOW()),
        ('ABT', '5', NOW()),
        ('MCD', '5', NOW()),
        ('SLB', '5', NOW()),
        ('C', '5', NOW()),
        ('BRK/B', '5', NOW()),
        ('BAC', '5', NOW()),
        ('RY', '5', NOW()),
        ('HD', '5', NOW()),
        ('DIS', '5', NOW()),
        ('TD', '5', NOW()),
        ('UTX', '5', NOW()),
        ('OXY', '5', NOW()),
        ('AXP', '5', NOW()),
        ('KFT', '5', NOW()),
        ('COP', '5', NOW()),
        ('MO', '5', NOW()),
        ('CAT', '5', NOW()),
        ('V', '5', NOW()),
        ('CMCSA', '5', NOW()),
        ('MMM', '5', NOW()),
        ('USB', '5', NOW()),
        ('AIG', '5', NOW()),
        ('EMC', '5', NOW()),
        ('CVS', '5', NOW()),
        ('BNS', '5', NOW()),
        ('UNH', '5', NOW()),
        ('BA', '5', NOW()),
        ('UPS', '5', NOW()),
        ('BMY', '5', NOW()),
        ('AMGN', '5', NOW()),
        ('UNP', '5', NOW()),
        ('GS', '5', NOW()),
        ('MA', '5', NOW()),
        ('EBAY', '5', NOW()),
        ('DD', '5', NOW()),
        ('HPQ', '5', NOW()),
        ('LLY', '5', NOW()),
        ('CL', '5', NOW()),
        ('SU', '5', NOW()),
        ('SPG', '5', NOW()),
        ('EPD', '5', NOW()),
        ('HON', '5', NOW()),
        ('LVS', '5', NOW()),
        ('ESRX', '5', NOW()),
        ('SBUX', '5', NOW()),
        ('NKE', '5', NOW()),
        ('ACN', '5', NOW()),
        ('F', '5', NOW()),
        ('MDT', '5', NOW()),
        ('SO', '5', NOW()),
        ('MON', '5', NOW()),
        ('TEVA', '5', NOW()),
        ('DOW', '5', NOW()),
        ('GILD', '5', NOW()),
        ('ABX', '5', NOW()),
        ('IMO', '5', NOW()),
        ('LOW', '5', NOW()),
        ('DHR', '5', NOW()),
        ('CNI', '5', NOW()),
        ('DB', '5', NOW()),
        ('TGT', '5', NOW()),
        ('PCLN', '5', NOW()),
        ('BMO', '5', NOW()),
        ('POT', '5', NOW()),
        ('MET', '5', NOW()),
        ('COST', '5', NOW()),
        ('EMR', '5', NOW()),
        ('BIDU', '5', NOW()),
        ('TXN', '5', NOW()),
        ('GM', '5', NOW()),
        ('TWX', '5', NOW()),
        ('CNQ', '5', NOW()),
        ('FCX', '5', NOW()),
        ('APC', '5', NOW()),
        ('PNC', '5', NOW()),
        ('PX', '5', NOW()),
        ('APA', '5', NOW()),
        ('BP', '5', NOW()),
        ('YUM', '5', NOW()),
        ('DTV', '5', NOW()),
        ('DE', '5', NOW()),
        ('NWSA', '5', NOW()),
        ('QQQ', '5', NOW()),
        ('MS', '5', NOW()),
        ('BCE', '5', NOW()),
        ('ENB', '5', NOW()),
        ('BIIB', '5', NOW()),
        ('TJX', '5', NOW()),
        ('KMB', '5', NOW()),
        ('CELG', '5', NOW()),
        ('BAX', '5', NOW()),
        ('TRP', '5', NOW()),
        ('NOV', '5', NOW()),
        ('HAL', '5', NOW()),
        ('D', '5', NOW()),
        ('GG', '5', NOW()),
        ('CM', '5', NOW()),
        ('MCI', '5', NOW()),
        ('WAG', '5', NOW()),
        ('RDS/A', '5', NOW()),
        ('DUK', '5', NOW()),
        ('LMT', '5', NOW()),
        ('DELL', '5', NOW()),
        ('EOG', '5', NOW()),
        ('AGN', '5', NOW()),
        ('FDX', '5', NOW()),
        ('ERIC', '5', NOW()),
        ('BK', '5', NOW()),
        ('SCCO', '5', NOW()),
        ('ITW', '5', NOW()),
        ('NEE', '5', NOW()),
        ('DVN', '5', NOW()),
        ('ADP', '5', NOW()),
        ('AMT', '5', NOW()),
        ('COV', '5', NOW()),
        ('INFY', '5', NOW()),
        ('ACE', '5', NOW()),
        ('BLK', '5', NOW()),
        ('EXC', '5', NOW()),
        ('TYC', '5', NOW()),
        ('BEN', '5', NOW()),
        ('PCP', '5', NOW()),
        ('TRV', '5', NOW()),
        ('COF', '5', NOW()),
        ('KMI', '5', NOW()),
        ('PRU', '5', NOW()),
        ('GIS', '5', NOW()),
        ('TWC', '5', NOW()),
        ('TRI', '5', NOW()),
        ('CVE', '5', NOW()),
        ('GD', '5', NOW()),
        ('PSA', '5', NOW()),
        ('AMX', '5', NOW()),
        ('CTL', '5', NOW()),
        ('VIAB', '5', NOW()),
        ('NSC', '5', NOW()),
        ('RAI', '5', NOW()),
        ('CSX', '5', NOW()),
        ('MFC', '5', NOW()),
        ('LYB', '5', NOW()),
        ('NEM', '5', NOW()),
        ('ISRG', '5', NOW()),
        ('STT', '5', NOW()),
        ('BBT', '5', NOW()),
        ('WLP', '5', NOW()),
        ('JCI', '5', NOW()),
        ('ADM', '5', NOW()),
        ('MPV', '5', NOW()),
        ('CTSH', '5', NOW()),
        ('MCK', '5', NOW()),
        ('CRM', '5', NOW()),
        ('COH', '5', NOW()),
        ('EP', '5', NOW()),
        ('GLW', '5', NOW()),
        ('CMI', '5', NOW()),
        ('SYK', '5', NOW()),
        ('AFL', '5', NOW()),
        ('CBS', '5', NOW()),
        ('BAM', '5', NOW()),
        ('TCK', '5', NOW()),
        ('ASML', '5', NOW()),
        ('CB', '5', NOW()),
        ('TMO', '5', NOW()),
        ('SE', '5', NOW()),
        ('FE', '5', NOW()),
        ('WMB', '5', NOW()),
        ('CCL', '5', NOW()),
        ('KMP', '5', NOW()),
        ('PSX', '5', NOW()),
        ('MRO', '5', NOW()),
        ('EQR', '5', NOW()),
        ('PCG', '5', NOW()),
        ('AEP', '5', NOW()),
        ('MMC', '5', NOW()),
        ('ECL', '5', NOW()),
        ('YHOO', '5', NOW()),
        ('SHPGY', '5', NOW()),
        ('CMCSK', '5', NOW()),
        ('APD', '5', NOW()),
        ('BHI', '5', NOW()),
        ('K', '5', NOW()),
        ('RTN', '5', NOW()),
        ('GSK', '5', NOW()),
        ('DFS', '5', NOW()),
        ('WPZ', '5', NOW()),
        ('SDRL', '5', NOW()),
        ('HES', '5', NOW());

CREATE USER 'administrator' @'localhost' IDENTIFIED BY 'LOCAL1234';

GRANT ALL PRIVILEGES ON libra.* TO 'administrator' @'localhost';